name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend   # your backend folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client   # 🔥 IMPORTANT FIX
        run: npx prisma generate

      # Optional (enable later when you add tests)
      # - name: Run tests
      #   run: npm test

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t backend-app .